import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,chmodSync,readFileSync} from 'node:fs';
import {dirname} from 'node:path';
import {createHash,randomBytes,scryptSync,timingSafeEqual} from 'node:crypto';
import {z} from 'zod';
export const defaults=JSON.parse(readFileSync(new URL('../content/site.json',import.meta.url),'utf8'));
const digest=v=>createHash('sha256').update(v).digest('hex');
export function hashPassword(password){const salt=randomBytes(24).toString('hex');return 'scrypt$'+salt+'$'+scryptSync(password,salt,64,{N:65536,maxmem:128*1024*1024}).toString('hex')}
export function checkPassword(password,stored){try{const [method,salt,expected]=stored.split('$');if(method!=='scrypt'||!/^[a-f0-9]{48}$/.test(salt)||!/^[a-f0-9]{128}$/.test(expected))return false;return timingSafeEqual(scryptSync(password,salt,64,{N:65536,maxmem:128*1024*1024}),Buffer.from(expected,'hex'))}catch{return false}}
const text=(min,max)=>z.string().trim().min(min).max(max);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Colombo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const date=z.string().refine(v=>{if(v==='')return true;if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const d=new Date(v+'T00:00:00Z');return !isNaN(d)&&d.toISOString().slice(0,10)===v&&v>=today()},'Choose a valid date today or later.');
export const inquirySchema=z.object({name:text(2,100),email:z.email().max(200),phone:z.string().trim().max(35).refine(v=>!v||/^\+?[\d ()-]{7,35}$/.test(v),'Use a valid phone number.'),service:z.enum(['multi-day','day-trip','airport']),vehicle:z.enum(['sedan','suv','van']),guests:z.number().int().min(1).max(6),days:z.number().int().min(1).max(30),date,route:z.string().max(80),pickup:text(2,180),destination:z.string().trim().max(180),notes:z.string().trim().max(2000),consent:z.literal(true),website:z.string().max(200).default('')}).strict().superRefine((v,ctx)=>{const issue=(path,message)=>ctx.addIssue({code:'custom',path:[path],message});if(v.guests>defaults.vehicles.find(x=>x.id===v.vehicle).capacity)issue('guests','Please choose a vehicle with enough seats.');if(v.route&&!defaults.routes.some(r=>r.slug===v.route))issue('route','Choose a suggested route or a custom route.');if(v.service!=='multi-day'&&v.days!==1)issue('days','Transfers and day trips use one service day.');if(v.service==='airport'&&v.destination.length<2)issue('destination','Please add your drop-off location.');});
export const settingsSchema=z.object({email:z.email().max(200),phone:z.string().regex(/^\+[1-9]\d{7,14}$/),prices:z.object({sedan:z.number().int().min(20).max(1000),suv:z.number().int().min(20).max(1000),van:z.number().int().min(20).max(1000)}).strict()}).strict();
export const statusSchema=z.object({status:z.enum(['new','contacted','quoted','confirmed','closed'])}).strict();
export function estimate(c,id,days){const v=c.vehicles.find(v=>v.id===id);if(!v||!Number.isInteger(days)||days<1||days>30)throw Error('Invalid estimate.');return {currency:'USD',dailyRate:v.price,days,total:v.price*days,type:'planning-estimate',vehicle:id}}
export function openStore(filename){mkdirSync(dirname(filename),{recursive:true,mode:0o700});const db=new DatabaseSync(filename);chmodSync(filename,0o600);db.exec("PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS inquiries(id TEXT PRIMARY KEY,created TEXT NOT NULL,status TEXT NOT NULL,payload TEXT NOT NULL,estimate TEXT,notification TEXT NOT NULL DEFAULT 'not-configured');CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,csrf TEXT NOT NULL,expires INTEGER NOT NULL,credential TEXT NOT NULL);CREATE TABLE IF NOT EXISTS limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,reset INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1),payload TEXT NOT NULL);");const credential=digest(process.env.ADMIN_PASSWORD_HASH||'');return {
 db,content(){const c=structuredClone(defaults),row=db.prepare('SELECT payload FROM settings WHERE id=1').get();if(row){const s=settingsSchema.parse(JSON.parse(row.payload));c.email=s.email;c.phone=s.phone;c.vehicles.forEach(v=>{v.price=s.prices[v.id]})}return c},
 saveSettings(value){db.prepare('INSERT INTO settings(id,payload) VALUES(1,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload').run(JSON.stringify(settingsSchema.parse(value)))},
 limit(key,max,window){const now=Date.now(),hash=digest(key);db.prepare('DELETE FROM limits WHERE reset<?').run(now);db.prepare('INSERT INTO limits(key,count,reset) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1').run(hash,now+window);return db.prepare('SELECT count FROM limits WHERE key=?').get(hash).count<=max},
 session(){const token=randomBytes(32).toString('hex'),csrf=randomBytes(32).toString('hex');db.prepare('DELETE FROM sessions WHERE expires<? OR credential!=?').run(Date.now(),credential);db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(digest(token),csrf,Date.now()+43200000,credential);return {token,csrf}},
 auth(token){return token?db.prepare('SELECT csrf FROM sessions WHERE token=? AND expires>? AND credential=?').get(digest(token),Date.now(),credential):null},
 logout(token){if(token)db.prepare('DELETE FROM sessions WHERE token=?').run(digest(token))},close(){db.close()}
}}
