import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,rmSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import {DatabaseSync} from 'node:sqlite';
import {createApp} from '../backend/server.mjs';
import {hashPassword,checkPassword,defaults,inquirySchema,estimate} from '../backend/store.mjs';
import {render} from '../dist/server/server.js';
const origin='http://localhost:3000',template=readFileSync('dist/client/template.html','utf8');
const inquiry={name:'Test Traveller',email:'traveller@example.com',phone:'',service:'multi-day',vehicle:'sedan',guests:2,days:7,date:'',route:'culture-and-tea-country',pickup:'Colombo Airport',destination:'Colombo Airport',notes:'Integration test only',consent:true,website:''};
async function appTest(run){const dir=mkdtempSync(join(tmpdir(),'serendib-test-'));process.env.APP_ORIGIN=origin;process.env.ADMIN_PASSWORD_HASH=hashPassword('Temporary test passphrase only');delete process.env.RESEND_API_KEY;const app=createApp({database:join(dir,'test.sqlite'),renderer:render,template});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;const req=(path,method='GET',body,headers={})=>fetch(base+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...headers},...(body===undefined?{}:{body:JSON.stringify(body)}),redirect:'manual'});try{await run({app,req,dir})}finally{await app.close();rmSync(dir,{recursive:true,force:true})}}
test('prices are per vehicle and validation rejects unsafe or impossible requests',()=>{assert.equal(estimate(defaults,'sedan',7).total,413);assert.equal(estimate(defaults,'suv',7).total,539);for(const value of [{...inquiry,price_per_person:1},{...inquiry,guests:4},{...inquiry,days:0},{...inquiry,days:31},{...inquiry,date:'2020-01-01'},{...inquiry,date:'2099-02-30'},{...inquiry,consent:false},{...inquiry,service:'airport',days:1,destination:''}])assert.equal(inquirySchema.safeParse(value).success,false);assert.equal(inquirySchema.safeParse({...inquiry,service:'airport',days:1,destination:'Galle'}).success,true)});
test('password hashes use fresh salts and reject incorrect passwords',()=>{const hash=hashPassword('a long test passphrase');assert.equal(checkPassword('a long test passphrase',hash),true);assert.equal(checkPassword('incorrect',hash),false);assert.notEqual(hash,hashPassword('a long test passphrase'));assert.equal(checkPassword('anything','not-a-hash'),false)});
test('enquiry privacy, server pricing, CSRF, settings, deletion and logout',()=>appTest(async({app,req})=>{
 for(const path of ['/api/inquiries','/api/trip-inquiries','/api/admin/inquiries']){const r=await req(path);assert.ok([401,404].includes(r.status));assert.doesNotMatch(await r.text(),/traveller@example.com/)}
 let r=await req('/api/inquiries','POST',inquiry,{Origin:'https://unrelated.example'});assert.equal(r.status,403);
 r=await req('/api/inquiries','POST',{...inquiry,price_per_person:1});assert.equal(r.status,422);
 r=await req('/api/inquiries','POST',inquiry);assert.equal(r.status,201);const {reference}=await r.json();assert.match(reference,/^[a-f0-9-]{36}$/);
 r=await req('/api/admin/login','POST',{password:'wrong'});assert.equal(r.status,401);
 r=await req('/api/admin/login','POST',{password:'Temporary test passphrase only'});assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);const cookie=r.headers.get('set-cookie').split(';')[0],{csrf}=await r.json(),headers={Cookie:cookie,'X-CSRF-Token':csrf};
 r=await req('/api/admin/inquiries','GET',undefined,headers);assert.equal(r.status,200);let d=await r.json();assert.equal(d.total,1);assert.equal(d.items[0].estimate.total,413);assert.equal(d.items[0].payload.email,inquiry.email);
 r=await req('/api/admin/inquiries/'+reference,'PATCH',{status:'quoted'},{Cookie:cookie});assert.equal(r.status,403);
 r=await req('/api/admin/inquiries/'+reference,'PATCH',{status:'quoted'},headers);assert.equal(r.status,200);
 const settings={email:'owner@example.com',phone:'+94710000000',prices:{sedan:60,suv:80,van:90}};r=await req('/api/admin/settings','PUT',settings,headers);assert.equal(r.status,200);
 r=await req('/api/estimate?vehicle=sedan&days=7');assert.equal((await r.json()).total,420);
 r=await req('/routes/culture-and-tea-country');const html=await r.text();assert.match(html,/\$420/);assert.match(html,/owner@example.com/);assert.doesNotMatch(html,/PRIVATE PREVIEW/);
 r=await req('/api/admin/inquiries','GET',undefined,headers);d=await r.json();assert.equal(d.items[0].estimate.total,413);
 r=await req('/api/admin/inquiries/'+reference,'DELETE',undefined,headers);assert.equal(r.status,200);assert.equal(app.store.db.prepare('SELECT COUNT(*) AS n FROM inquiries').get().n,0);
 r=await req('/api/admin/logout','POST',{},headers);assert.equal(r.status,200);assert.equal((await req('/api/admin/inquiries','GET',undefined,headers)).status,401);
}));
test('public pages render on the server, assets resolve, and missing pages return 404',()=>appTest(async({req})=>{const pages=['/','/routes','/plan','/about','/terms','/privacy','/admin',...defaults.routes.map(r=>'/routes/'+r.slug)];for(const p of pages){const r=await req(p);assert.equal(r.status,200,p);const html=await r.text();assert.match(html,/<title>/);assert.match(html,/<main id="main">/);assert.doesNotMatch(html,/<!--site-/);for(const [,url] of html.matchAll(/(?:src|href)="(\/(?:assets|images|fonts)\/[^"?#]+)"/g))assert.equal((await req(url)).status,200,url)}assert.equal((await req('/not-a-page')).status,404);assert.equal((await req('/.env')).status,404);assert.equal((await req('/data/serendib.sqlite')).status,404);assert.equal((await req('/api/bookings/create-checkout','POST',{})).status,410);assert.match(await (await req('/robots.txt')).text(),/Disallow: \//);assert.match(await (await req('/sitemap.xml')).text(),/culture-and-tea-country/)}));
test('enquiry rate limiting persists and airport enquiries do not invent a fare',()=>appTest(async({app,req})=>{for(let i=0;i<8;i++)assert.equal((await req('/api/inquiries','POST',{...inquiry,service:'airport',days:1})).status,201);assert.equal((await req('/api/inquiries','POST',inquiry)).status,429);assert.equal(app.store.db.prepare('SELECT estimate FROM inquiries LIMIT 1').get().estimate,null);assert.ok(app.store.db.prepare('SELECT COUNT(*) AS n FROM limits').get().n>0)}));
test('live SQLite backup restores enquiries and settings',()=>appTest(async({app,req,dir})=>{await req('/api/inquiries','POST',inquiry);app.store.saveSettings({email:'owner@example.com',phone:'+94710000000',prices:{sedan:60,suv:80,van:90}});const destination=join(dir,'backup.sqlite');execFileSync(process.execPath,['scripts/backup.mjs',destination],{env:{...process.env,DATABASE_PATH:join(dir,'test.sqlite')},stdio:'pipe'});assert.ok(existsSync(destination));const restored=new DatabaseSync(destination);assert.equal(restored.prepare('SELECT COUNT(*) AS n FROM inquiries').get().n,1);assert.match(restored.prepare('SELECT payload FROM settings').get().payload,/owner@example.com/);restored.close()}));
test('private review pages clearly identify the preview and include local fonts',()=>{assert.match(readFileSync('dist/client/index.html','utf8'),/PRIVATE PREVIEW/);assert.match(readFileSync('dist/client/plan/index.html','utf8'),/does not send or save/);for(const font of ['dm-sans.woff2','dm-serif.woff2'])assert.equal(readFileSync(resolve('dist/client/fonts',font)).subarray(0,4).toString(),'wOF2')});
