// Distinct original planning articles, not translated or duplicate regional pages.
export const guideHub='/sri-lanka-travel-guide';
export const planningGuides=[
{path:'/sri-lanka-holidays-from-uk',label:'Planning from the UK',title:'Sri Lanka Holidays from the UK: Driver & Route Planning',description:'Plan the Sri Lanka transport part of your UK holiday: compare 7 and 10 day routes, allow for arrival-day rest and understand a private driver quote.',intro:'Planning a Sri Lanka holiday from the UK? Start with the days you will actually spend on the island. Serendib Local helps with private transport requests and route planning; international flights, accommodation and activities are separate.',sections:[
{heading:'Count nights on the island, not days away from home',paragraphs:['Write down your Sri Lanka arrival and departure in local time. An overnight journey and a connecting flight can make a week away feel much shorter on the ground. Leave the first day flexible for immigration, baggage and rest instead of building it around a timed attraction booking.','For a late arrival, discuss a first night near the airport. If your return flight leaves early, decide on the final overnight stop before booking hotels. A long hill-country drive followed by an international flight is a different proposition from a relaxed final day near Colombo.']},
{heading:'A week of culture or a longer coastal finish',paragraphs:['With seven days, our culture-and-tea route uses Sigiriya, Kandy and Nuwara Eliya as three bases. Two nights at each gives you a day between transfers. It leaves Ella and the coast for another visit rather than fitting everything into the same week.','With ten days, the longer route adds Ella and Galle. If you have a fortnight, discuss extra nights and mark the days you do not need a vehicle. A ten-day transport estimate is not a fourteen-day package price.'],links:[['/routes/culture-and-tea-country','Compare the seven-day culture and tea route'],['/routes/island-at-your-pace','Explore the ten-day route']]},
{heading:'Compare the transport quote in one currency',paragraphs:['Website prices are USD guide amounts for the whole vehicle, not GBP prices or per-person holiday packages. When comparing a UK package, separate flights, hotels, meals and attractions from its car-and-driver portion.','Ask for the final payment currency, included hours and kilometres, driver costs, parking, tolls and cancellation terms. For a budget in pounds, check your payment provider’s current conversion and fees. We do not promise a fixed GBP equivalent.'],links:[['/sri-lanka-driver-cost','See costs and inclusions']]},
{heading:'Before confirming your holiday',paragraphs:['Check current FCDO advice, your airline itinerary and any transit-country requirements. Entry requirements depend on your travel documents, not simply living in the UK. We do not provide flights or visa processing.','Send your local arrival and departure times, group, luggage and preferred overnight stops. If you are combining family visits and sightseeing, mark each part so the quote reflects the transport you need.'],links:[['https://www.gov.uk/foreign-travel-advice/sri-lanka','Official UK travel advice'],['/colombo-airport-transfers','Plan your airport pickup']]}
],related:['/sri-lanka-family-travel','/sri-lanka-holidays-from-australia']},
{path:'/sri-lanka-holidays-from-australia',label:'Planning from Australia',title:'Sri Lanka Holidays from Australia: Private Transport Guide',description:'Plan Sri Lanka transport from Australia with arrival-day flexibility, family luggage checks, touring around family visits and clear USD guide prices.',intro:'Build your Sri Lanka holiday around your arrival, your group and time in each place. This guide helps you plan private transport from Australia, whether you want a sightseeing trip or time visiting family between journeys.',sections:[
{heading:'Give the arrival day a lighter job',paragraphs:['Use the Sri Lanka date and local landing time on your flight itinerary when requesting a pickup. Your departure date in Australia alone is not enough. If flights are still provisional, tell us so the first road journey can remain flexible.','An airport pickup to your accommodation and a full touring day are different services. Consider a short first transfer and a rest before beginning a longer route. Meeting arrangements, delays and included waiting time are confirmed in the transfer quote.'],links:[['/colombo-airport-transfers','Airport-transfer request checklist']]},
{heading:'Combine touring with time visiting relatives',paragraphs:['List the days you will stay with relatives, the days you want a driver and any transfers between private addresses. We can then discuss separate transfers or a continuous hire. A no-driving day does not automatically reduce a continuous-hire price unless agreed.','For an extended family group, send passenger and bag numbers together. Children’s ages, a folded stroller and mobility equipment can change the vehicle needed. Child seats and accessibility arrangements require specific confirmation.'],links:[['/sri-lanka-family-travel','Plan seats, luggage and breaks']]},
{heading:'Choose the route around your available touring days',paragraphs:['A seven-day culture-and-tea journey uses three bases. A ten-day route adds Ella and the coast, with more accommodation changes. If family events already occupy part of your visit, count only the remaining days when choosing a route.','For a shorter break, the five-day Galle and Mirissa plan focuses on two coastal bases. Tell us which places are essential and which you would happily leave out. Weather and conditions for your actual dates should inform the final plan.'],links:[['/sri-lanka-itinerary-guide','Compare five, seven and ten days']]},
{heading:'Budget in AUD; confirm the payment currency',paragraphs:['The website’s dollar figures are US dollars per vehicle, not Australian dollars per person. Flights, accommodation, meals and activities are outside those estimates. Check conversion costs with your payment provider when comparing against an AUD budget.','Ask for the final transport amount and terms in writing. We take no payment on this website, and an enquiry does not reserve a driver.'],links:[['/sri-lanka-driver-cost','Understand whole-vehicle prices']]},
{heading:'Check official information for your passport',paragraphs:['Use Smartraveller for current advice and check your airline’s requirements. Travelling from Australia does not determine entry eligibility: check the rules for the passport you will use.','Send the group, bags, flights, fixed family commitments and desired route. We check transport availability for those dates; flights, visa services and an Australian-based support office are not part of our offer.'],links:[['https://www.smartraveller.gov.au/destinations/asia/sri-lanka','Official Australian travel advice']]}
],related:['/sri-lanka-family-travel','/colombo-airport-to-galle']},
{path:'/sri-lanka-trip-from-india',label:'Planning from India',title:'Sri Lanka Trip from India: 5–7 Day Transport Planning',description:'Plan a Sri Lanka trip from India with a realistic 5 or 7 day route, private car-and-driver costs, airport pickup details and family transport requests.',intro:'For a Sri Lanka trip from India, choose your priorities before filling every day. Private transport connects your overnight bases; flights, hotels, meals and tickets remain separate parts of the holiday budget.',sections:[
{heading:'Five days and seven days offer different holidays',paragraphs:['Our five-day suggestion focuses on Galle and Mirissa for a coastal break with fewer hotel changes. If the Cultural Triangle and tea country are your priority, start with the seven-day route through Sigiriya, Kandy and Nuwara Eliya.','Arrival and departure are not guaranteed full sightseeing days. Send the flight times before deciding on your first and last accommodation. If you have only four usable days, shorten the route instead of squeezing seven days of stops into it.'],links:[['/routes/south-coast-slowly','Five-day coastal itinerary'],['/routes/culture-and-tea-country','Seven-day culture and tea itinerary']]},
{heading:'Request the right vehicle for your group',paragraphs:['Share the number of adults and children and list large bags. A sedan estimate is useful only if the vehicle can carry your group and luggage. If relatives arrive on different flights, specify whether you want separate pickups.','Tell us about meal-stop preferences, vegetarian food requests, walking limitations and breaks. These inform the route; meals and dietary guarantees are not included in transport. Language requests need confirmation: Hindi, Tamil or another language is not automatically available with every driver.'],links:[['/sri-lanka-family-travel','Family transport checklist']]},
{heading:'USD prices are for the whole vehicle',paragraphs:['Our guide amounts are not INR prices, per-person fares or all-inclusive packages. Divide the total between your group only after confirming the vehicle and service days.','Compare fuel, driver meals and accommodation, parking, tolls, included hours and kilometres. Budget separately for hotels, meals, entry tickets and specialist guides. Check conversion and payment fees with your provider instead of relying on a fixed rupee conversion.'],links:[['/sri-lanka-driver-cost','Compare transport inclusions and totals']]},
{heading:'Religious and special-interest stops need a specific request',paragraphs:['Name any temples or other places that matter to your journey. We assess the driving route, but transport does not automatically include a guided pilgrimage, specialist interpretation or attraction access. Any separate guide and opening arrangements need checking.','The same applies to train seats and wildlife outings. Keep the main plan workable by road until optional activities are confirmed. Send your exact hotel names, flights, group and luggage for a quote. We do not arrange international flights or process visas.'],links:[['https://www.hcicolombo.gov.in/','High Commission of India in Colombo'],['/colombo-airport-to-sigiriya','Plan a transfer to Sigiriya']]}
],related:['/sri-lanka-family-travel','/colombo-airport-to-sigiriya']},
{path:'/sri-lanka-family-travel',label:'Travelling with family',title:'Sri Lanka Family Travel: Private Driver, Seats & Luggage',description:'Plan family travel in Sri Lanka with realistic overnight stops, luggage space, child-seat requests, rest breaks and a clear private transport quote.',intro:'A family route works best when the vehicle, luggage space and daily pace fit the people travelling. Start with everyone’s needs, then choose the route and vehicle together.',sections:[
{heading:'Seats are only half the space calculation',paragraphs:['Tell us the number of adults and children and list suitcases, cabin bags, strollers and other equipment. A published passenger capacity does not confirm that all your belongings will fit in the actual vehicle.','For child-seat requests, provide the child’s age and approximate size. Confirm the seat type and fitting before booking; availability is not guaranteed. A child seat takes passenger space, so do not count a child beyond the agreed seating capacity.'],links:[['/sri-lanka-private-driver','Vehicle options and luggage guidance']]},
{heading:'Fewer bases leave more breathing room',paragraphs:['Two nights in a base can be easier than packing every morning. Our seven-day culture-and-tea plan uses three bases and the five-day coastal plan uses two. The ten-day loop offers more variety but involves more hotel changes.','Build meals and breaks into transfer days. If winding roads are uncomfortable for someone, mention this before deciding how much hill country to include. The route can be shortened; it need not include every famous stop.'],links:[['/sri-lanka-itinerary-guide','Compare overnight bases']]},
{heading:'Plan for mixed ages and interests',paragraphs:['Identify which outings everyone wants and which could be optional. Ask accommodation providers directly about steps and room access. Arranging a vehicle does not confirm the accessibility of a property or attraction.','A driver provides agreed transport, not childcare, medical support or automatic attraction guiding. Special requirements should be discussed before you commit so we can check whether they can be accommodated.']},
{heading:'Keep the airport day simple',paragraphs:['Share flight details and the exact accommodation address. After a late flight, consider a shorter first drive rather than adding sightseeing after immigration and baggage collection. Agree the meeting method and waiting policy.','If family members have different flights, list each one. An extra airport run is a separate request, not an assumed part of the route.'],links:[['/colombo-airport-transfers','Airport pickup checklist']]},
{heading:'One transport price with a clear scope',paragraphs:['Guide prices are for a vehicle, not each family member. The final quote depends on the vehicle that fits, the route and your dates. Hotels, food, tickets and activities remain separate.','Send your group and luggage details, seat or mobility requests, overnight bases and flights. We will check availability and confirm the transport scope before booking.'],links:[['/sri-lanka-driver-cost','Read the driver-cost guide']]}
],related:['/sri-lanka-holidays-from-uk','/sri-lanka-holidays-from-australia','/sri-lanka-trip-from-india']},
{path:'/colombo-airport-to-galle',label:'CMB airport to Galle',service:'airport',title:'Colombo Airport to Galle: Private Transfer Planning',description:'Request a Colombo airport to Galle private transfer. Check CMB pickup, Galle Fort or coastal hotel drop-off, luggage, waiting time and quote inclusions.',intro:'Continuing from Bandaranaike International Airport (CMB) to Galle? Share your flight, exact hotel and luggage to request a private transfer. Pickup arrangements and price are confirmed for your journey.',sections:[
{heading:'CMB airport is different from a Colombo city pickup',paragraphs:['Specify the airport and flight details. A quote from a Colombo hotel is not the same journey as a CMB pickup. Say whether your destination is Galle Fort, a Galle-area hotel or a property farther along the coast.','Unawatuna, Weligama and Mirissa need their own destination details. A property name and address prevent an approximate place name from becoming a different transfer on arrival.']},
{heading:'Plan the first stop around your flight',paragraphs:['Allow for immigration, baggage and meeting the driver before setting off. We confirm expected journey duration for the date and route. A map estimate is not a guaranteed hotel arrival time.','After a late flight, discuss an airport-area overnight stay and a next-day departure if you prefer. Check hotel arrival arrangements separately: a transfer does not reserve a room or guarantee early check-in.']},
{heading:'Agree the final drop-off and extra stops',paragraphs:['For a Galle Fort stay, provide the exact property so practical drop-off arrangements can be checked. Where vehicle access is restricted, agree where the transfer ends and how to contact your accommodation.','A meal break, shopping stop or sightseeing detour needs discussion before the quote is accepted. A point-to-point transfer is not an unlimited day tour. Tell us if sightseeing is part of the request so time and charges can be assessed.']},
{heading:'Check the whole transfer quote',paragraphs:['Confirm the vehicle, passenger and bag capacity, meeting point, contact method, waiting allowance, tolls, parking and destination. Ask what happens if the flight is delayed and whether extra waiting is chargeable.','This transfer is quote-only. The daily sedan guide rate applies to multi-day planning; it is not an airport-to-Galle fare. Child seats and unusual luggage need separate confirmation.'],links:[['/colombo-airport-transfers','Full airport-transfer checklist']]},
{heading:'Continue along the coast or finish a longer route',paragraphs:['The five-day coastal suggestion combines Galle and Mirissa as two bases. If Galle ends a longer journey, plan your airport return around the airline’s check-in requirements and allow for road delays.','Send dates, flight details, your destination and group to request availability. Hotels and activities are separate.'],links:[['/routes/south-coast-slowly','Five-day south-coast itinerary'],['/routes/island-at-your-pace','Ten-day route finishing around Galle']]}
],related:['/colombo-airport-to-sigiriya','/sri-lanka-family-travel']},
{path:'/colombo-airport-to-sigiriya',label:'CMB airport to Sigiriya',service:'airport',title:'Colombo Airport to Sigiriya: Private Transfer Guide',description:'Plan a Colombo airport to Sigiriya private transfer with flight timing, exact hotel drop-off, luggage and a realistic start to your Cultural Triangle trip.',intro:'A CMB airport transfer to Sigiriya can start your Cultural Triangle journey. Shape the first road day around your flight and rest needs, then confirm the vehicle, destination and price in writing.',sections:[
{heading:'Use your hotel’s exact location',paragraphs:['Sigiriya, Dambulla and Habarana can all feature in a Cultural Triangle plan, but they are different drop-offs. Send your property name and address, not just the attraction you intend to visit.','If accommodation is undecided, tell us the area you are considering. We can discuss the route, but a final transfer quote requires a confirmed destination.']},
{heading:'A transfer is not an arrival-day sightseeing promise',paragraphs:['Landing is followed by immigration, baggage and meeting your driver. Consider whether you want the longer onward journey immediately or a night near the airport before continuing.','Avoid making a timed attraction booking depend on an international flight being punctual. The transfer does not include entry to Sigiriya or Dambulla, specialist guiding or guaranteed opening arrangements.']},
{heading:'Keep stops and waiting explicit',paragraphs:['Mention any meal or sightseeing stop you want on the way. An attraction changes the schedule and waiting time, so it needs assessment before the quote is accepted.','Confirm your meeting point, contact method and delayed-flight policy in writing. Provide bag sizes and passenger numbers together. Child-seat requests and vehicle suitability are checked for your actual dates.'],links:[['/colombo-airport-transfers','Check airport pickup details']]},
{heading:'Choose a one-way transfer or a multi-day hire',paragraphs:['If you only need to reach your hotel, request one-way transport. If you want a driver through Sigiriya, Kandy and tea country, share the complete overnight route so we can quote the whole arrangement.','The daily planning rate is not a fixed airport-to-Sigiriya fare. Check tolls, parking, waiting, stops, payment currency and cancellation terms. Hotels, meals and entry tickets are separate.'],links:[['/sri-lanka-private-driver','How multi-day hire works'],['/sri-lanka-driver-cost','Driver costs and inclusions']]},
{heading:'Build the next days around a base',paragraphs:['Our seven-day route starts with two nights around Sigiriya before Kandy and Nuwara Eliya. The ten-day suggestion adds Ella and the coast. Both can be adapted to your flights and priorities.','If arrival leaves little usable time, revise the first day rather than adding stops. Include your final departure flight in the enquiry so the first transfer fits the complete trip.'],links:[['/routes/culture-and-tea-country','Seven-day culture and tea route'],['/routes/island-at-your-pace','Ten-day island route']]}
],related:['/colombo-airport-to-galle','/sri-lanka-trip-from-india']}
];
export const planningPaths=[guideHub,...planningGuides.map(g=>g.path)];
