import React from 'react';
import {ArrowUpRight} from 'lucide-react';
import {guideHub,planningGuides} from '../../shared/guides.mjs';
const Link=({href,children})=><a className="text-link" href={href}>{children}<ArrowUpRight size={16}/></a>;
const cards=guides=><div className="three-grid guide-cards">{guides.map(g=><article key={g.path}><h3><a href={g.path}>{g.label}</a></h3><p>{g.description}</p><Link href={g.path}>Read the guide</Link></article>)}</div>;
export default function PlanningGuides({path,c}){
 const guide=planningGuides.find(g=>g.path===path);
 if(path===guideHub)return <>
  <section className="container page-heading"><p className="eyebrow">PRACTICAL HELP BEFORE YOU TRAVEL</p><h1>Your Sri Lanka<br/><em>travel planning guide.</em></h1><p>Choose a route, understand your transport budget and make the first airport pickup simpler. Start with the question you are trying to answer.</p></section>
  <section className="container section guide-hub"><h2>Planning from abroad</h2><p>These guides cover the transport part of your holiday. They do not include flights, hotels or visa services.</p>{cards(planningGuides.slice(0,3))}
  <h2>Family journeys and airport routes</h2>{cards(planningGuides.slice(3))}
  <h2>Start with the essentials</h2><div className="guide-essentials"><Link href="/sri-lanka-private-driver">How private driver hire works</Link><Link href="/sri-lanka-driver-cost">Vehicle prices and inclusions</Link><Link href="/sri-lanka-itinerary-guide">Compare five, seven and ten days</Link><Link href="/colombo-airport-transfers">Airport pickup checklist</Link></div>
  <h2>Visiting from another country?</h2><p>Travellers from Germany, France, the Netherlands, Russia, China, the United States and Canada can use the same route, transfer and cost guides. Tell us your local arrival time, travel dates, passenger and luggage numbers, and preferred language when you enquire. Driver language availability must be checked before booking.</p><p>Our current website and written planning information are in English. USD guide prices are for the whole vehicle; they are not prices in euros, Canadian or Australian dollars, or your home currency. Confirm the final payment currency and check conversion fees with your payment provider.</p><p>If you are visiting relatives as well as sightseeing, tell us which days need transport. For a first visit, compare the overnight bases before selecting attractions. Your passport and transit route determine which official entry information you need to check.</p>
  <Link href="/plan">Ask about your dates and route</Link></section></>;
 if(!guide)return null;
 const related=guide.related.map(p=>planningGuides.find(g=>g.path===p)).filter(Boolean);
 return <><section className="container page-heading"><p className="eyebrow">SERENDIB LOCAL · TRANSPORT PLANNING</p><h1>{guide.title}</h1><p>{guide.intro}</p><a className="button" href={'/plan?service='+(guide.service||'multi-day')}>Request a written quote<ArrowUpRight size={17}/></a></section>
 <section className="container editorial section"><div><nav className="guide-toc" aria-label="On this page"><h2>In this guide</h2><ul>{guide.sections.map((s,i)=><li key={s.heading}><a href={'#section-'+(i+1)}>{s.heading}</a></li>)}</ul></nav>{guide.sections.map((s,i)=><section key={s.heading} id={'section-'+(i+1)}><h2>{s.heading}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}{s.links&&<div className="guide-links">{s.links.map(([href,label])=><Link key={href} href={href}>{label}</Link>)}</div>}</section>)}<p className="small-copy">Prepared by Serendib Local · Updated 18 September 2026. We confirm availability and the final transport arrangements for your dates before booking.</p></div>
 <aside className="editorial-aside"><p className="eyebrow">YOUR NEXT STEP</p><h3>A route that fits.<br/>A clear quote.</h3>{guide.service==='airport'?<p>This transfer is quote-only. Send your flight, exact destination, passenger count and luggage.</p>:<p>Multi-day sedan guide from USD {c.vehicles.find(v=>v.id==='sedan').price} per vehicle per day. Hotels and activities separate; dates, route and availability confirmed before booking.</p>}<Link href={'/plan?service='+(guide.service||'multi-day')}>Request availability</Link><hr/><Link href="/sri-lanka-driver-cost">Costs and inclusions</Link><Link href={guideHub}>All planning guides</Link></aside></section>
 <section className="container section guide-hub"><h2>Keep planning</h2>{cards(related)}</section></>;
}
