// Detailed package data with itinerary, included/excluded, multi-currency pricing.
// Duration groups: "3-5" | "6-8" | "9+"
// Types: couples | family | solo | adventure | wellness | culture

export const PACKAGES = [
  {
    slug: "real-sri-lanka",
    label: "Most Popular",
    title: "The Real Sri Lanka",
    tagline: "The classic loop, done the local way.",
    days: 10,
    durationLabel: "10 days",
    durationGroup: "9+",
    tags: ["family", "culture", "couples"],
    tagLabels: ["Family", "Culture", "Couples"],
    price: { USD: 1290, GBP: 1020, EUR: 1180 },
    priceNote: "per person, twin share",
    blurb:
      "Kandy, tea hills, the Ella train, safari and a southern beach — but via village homestays, family kitchens and roads the buses can't fit down.",
    image:
      "https://images.unsplash.com/photo-1574611122955-5baa61496637?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1Nzh8MHwxfHNlYXJjaHwyfHxzcmklMjBsYW5rYSUyMHRyYWlufGVufDB8fHx8MTc3NjQ4NDAwM3ww&ixlib=rb-4.1.0&q=85",
    highlights: [
      "Private driver-guide for the full 10 days",
      "Ella → Nuwara Eliya on the Blue Train (reserved window seat)",
      "Village homestay in a cinnamon-growing family",
      "Udawalawe safari with an off-grid local tracker",
    ],
    itinerary: [
      { day: 1, title: "Welcome to Colombo", desc: "Airport pickup, gentle walking tour of Pettah bazaar, first rice & curry in a local canteen.", meals: "Dinner", stay: "Boutique hotel, Colombo" },
      { day: 2, title: "Sigiriya via Dambulla caves", desc: "Scenic drive north. Climb the Dambulla cave temples at sunset, stay at the foot of Lion Rock.", meals: "Breakfast", stay: "Eco-lodge, Sigiriya" },
      { day: 3, title: "Sigiriya rock & village cycle", desc: "Sunrise climb of Sigiriya. Afternoon cycle through paddy fields with a local guide, cooking class with his mum.", meals: "Breakfast, Lunch", stay: "Eco-lodge, Sigiriya" },
      { day: 4, title: "Kandy & Temple of the Tooth", desc: "Drive via spice gardens to Kandy. Evening Kandyan dance ceremony, lakeside walk.", meals: "Breakfast", stay: "Heritage guesthouse, Kandy" },
      { day: 5, title: "Kandy → Hill Country by train", desc: "Board the Blue Train to Nanu Oya. Cloud forests, tea estates, door-hanging photos.", meals: "Breakfast", stay: "Tea bungalow, Nuwara Eliya" },
      { day: 6, title: "Tea country walk & Haputale", desc: "Walk with a Tamil tea-picker family, factory tour, sunrise at Lipton's Seat.", meals: "Breakfast, Lunch", stay: "Tea bungalow, Haputale" },
      { day: 7, title: "Ella's waterfalls & Nine Arches", desc: "Short hike to Ravana Falls, lazy afternoon at Nine Arches Bridge.", meals: "Breakfast", stay: "Ella hideaway" },
      { day: 8, title: "Udawalawe safari", desc: "Early safari with our favourite tracker — elephants, eagles, maybe a leopard if you're lucky.", meals: "Breakfast, Lunch", stay: "Safari tent, Udawalawe" },
      { day: 9, title: "South coast chill", desc: "Drive to Mirissa. Sunset on a fisherman's beach, seafood BBQ with the local catch.", meals: "Breakfast, Dinner", stay: "Beach villa, Weligama" },
      { day: 10, title: "Galle Fort & flight home", desc: "Morning stroll around Galle Fort's ramparts, slow coffee, transfer to airport.", meals: "Breakfast", stay: "—" },
    ],
    included: [
      "Private air-conditioned vehicle + English-speaking driver-guide",
      "All accommodation (twin share) in boutique/homestay properties",
      "Daily breakfast + 4 traditional dinners",
      "Blue Train reserved seat (Kandy → Nanu Oya)",
      "Sigiriya, Dambulla, Temple of the Tooth entry fees",
      "Udawalawe safari jeep & park fees",
      "Village cycling + cooking class",
      "Airport pickup & drop-off",
      "24/7 WhatsApp support",
    ],
    excluded: [
      "International flights",
      "Visa (ETA, ~USD 50 online)",
      "Lunches (unless stated) — we'll recommend the best local spots",
      "Alcoholic drinks",
      "Travel insurance",
      "Tips for driver-guide (optional)",
    ],
  },
  {
    slug: "hidden-lanka",
    label: "Most Unique",
    title: "Hidden Lanka",
    tagline: "Zero tourist buses. All the real stuff.",
    days: 12,
    durationLabel: "12 days",
    durationGroup: "9+",
    tags: ["adventure", "solo", "culture"],
    tagLabels: ["Adventure", "Solo-friendly", "Culture"],
    price: { USD: 1590, GBP: 1260, EUR: 1450 },
    priceNote: "per person, twin share",
    blurb:
      "Jaffna, Mannar, Knuckles mountains, village homestays and the wildlife most travellers never hear about. For travellers who want stories, not selfies.",
    image:
      "https://images.unsplash.com/photo-1534545872802-0579930815c2?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA2MTJ8MHwxfHNlYXJjaHwzfHxzcmklMjBsYW5rYSUyMGVsZXBoYW50fGVufDB8fHx8MTc3NjQ4Mzk5Nnww&ixlib=rb-4.1.0&q=85",
    highlights: [
      "Tamil homestay in Jaffna — rarely visited by tourists",
      "Wild elephants at Wasgamuwa (no jeep crowds)",
      "2-day trek in the Knuckles range with a village guide",
      "Island-hopping off Mannar by local fishing boat",
    ],
    itinerary: [
      { day: 1, title: "Colombo arrival", desc: "Gentle intro day. Street-food crawl with Kasun through Galle Face.", meals: "Dinner", stay: "Colombo boutique" },
      { day: 2, title: "Drive north to Anuradhapura", desc: "Ancient stupas at golden hour. Cycle among ruins.", meals: "Breakfast", stay: "Anuradhapura eco" },
      { day: 3, title: "Jaffna & Tamil culture", desc: "Drive to the deep north. Visit the Nallur temple, dinner with a Tamil family.", meals: "Breakfast, Dinner", stay: "Jaffna homestay" },
      { day: 4, title: "Delft Island by ferry", desc: "Wild ponies, Baobab trees, coral-wall houses. Pure time warp.", meals: "Breakfast, Lunch", stay: "Jaffna homestay" },
      { day: 5, title: "Mannar island & flamingos", desc: "Boat trip among flamingo flocks, Baobab forest, Adam's Bridge sands.", meals: "Breakfast", stay: "Mannar guest lodge" },
      { day: 6, title: "Wasgamuwa wild elephants", desc: "Safari in the park no one visits — often we're the only jeep there.", meals: "Breakfast", stay: "Forest tent" },
      { day: 7, title: "Knuckles village trek day 1", desc: "Walk into Meemure, 18km through cardamom forests with a village guide.", meals: "All", stay: "Village family home" },
      { day: 8, title: "Knuckles trek day 2", desc: "Sunrise at the viewpoint, descend to Corbett's Gap.", meals: "All", stay: "Kandy area" },
      { day: 9, title: "Kandy + hill country", desc: "Temple of the Tooth, then slow train to tea country.", meals: "Breakfast", stay: "Tea estate bungalow" },
      { day: 10, title: "Ella & waterfalls", desc: "Nine Arches, Little Adam's Peak at sunrise.", meals: "Breakfast", stay: "Ella cabin" },
      { day: 11, title: "South coast surprise", desc: "Secret bay near Tangalle — no hotels, just us and a fisherman's shack.", meals: "Breakfast, Dinner", stay: "Beach hut" },
      { day: 12, title: "Galle & departure", desc: "Slow morning in Galle Fort, airport transfer.", meals: "Breakfast", stay: "—" },
    ],
    included: [
      "Private 4WD-capable vehicle + driver-guide",
      "12 nights in mix of homestays, eco-lodges & tented camps",
      "Daily breakfast + 7 dinners + 3 lunches",
      "All park fees (Wasgamuwa + Knuckles)",
      "2-day Knuckles trek with local guide + porter",
      "Delft Island ferry + Mannar boat trip",
      "Cultural entry fees (Anuradhapura, Nallur, Temple of the Tooth)",
      "Airport pickup & drop-off",
      "24/7 WhatsApp support",
    ],
    excluded: [
      "International flights",
      "Visa (ETA, ~USD 50 online)",
      "Remaining lunches",
      "Alcoholic drinks",
      "Travel insurance",
      "Optional tips",
    ],
  },
  {
    slug: "slow-and-savour",
    label: "Best for Couples",
    title: "Slow & Savour",
    tagline: "Boutique villas, sunsets, Ayurveda.",
    days: 8,
    durationLabel: "8 days",
    durationGroup: "6-8",
    tags: ["couples", "wellness"],
    tagLabels: ["Couples", "Wellness"],
    price: { USD: 1180, GBP: 935, EUR: 1080 },
    priceNote: "per person, twin share",
    blurb:
      "A quieter, softer Sri Lanka. Hill-country hideaways, private beach villas, one authentic Ayurveda day and sunset dinners on the sand.",
    image:
      "https://images.unsplash.com/photo-1653959747793-c7c3775665f0?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1NTJ8MHwxfHNlYXJjaHwzfHxzcmklMjBsYW5rYSUyMGJlYWNofGVufDB8fHx8MTc3NjQ4NDAwM3ww&ixlib=rb-4.1.0&q=85",
    highlights: [
      "Boutique tea-estate bungalow (just 4 rooms)",
      "Private Ayurveda consultation + full-day treatment",
      "Beachfront villa with your own plunge pool",
      "Sunset seafood dinner on the sand",
    ],
    itinerary: [
      { day: 1, title: "Arrival & Colombo", desc: "Airport pickup, quiet welcome dinner.", meals: "Dinner", stay: "Colombo boutique" },
      { day: 2, title: "To the tea hills", desc: "Scenic drive via Kitulgala. Arrive at your tea-estate bungalow for afternoon tea.", meals: "Breakfast, Dinner", stay: "Tea bungalow" },
      { day: 3, title: "Tea walk & high-tea experience", desc: "Gentle plantation walk, factory tour, full colonial high-tea spread.", meals: "Breakfast, Lunch", stay: "Tea bungalow" },
      { day: 4, title: "Ella slow day", desc: "Little Adam's Peak sunrise (optional), cooking class, private Blue Train ride.", meals: "Breakfast, Dinner", stay: "Ella hideaway" },
      { day: 5, title: "Ayurveda day", desc: "Private consultation with an Ayurvedic doctor, 3-hour treatment, herbal lunch.", meals: "Breakfast, Lunch", stay: "Wellness retreat" },
      { day: 6, title: "Down to the south coast", desc: "Scenic drive to the beach. Afternoon snorkel or hammock nap.", meals: "Breakfast", stay: "Beach villa, Weligama" },
      { day: 7, title: "Beach, whales & sunset dinner", desc: "Optional dawn whale watch, lazy afternoon, private seafood BBQ on the sand.", meals: "Breakfast, Dinner", stay: "Beach villa" },
      { day: 8, title: "Galle Fort & departure", desc: "Galle Fort breakfast, antique shopping, airport transfer.", meals: "Breakfast", stay: "—" },
    ],
    included: [
      "Private vehicle + driver-guide for all transfers",
      "7 nights in boutique villas, tea bungalow, beach villa",
      "Daily breakfast + 4 dinners + 2 lunches",
      "Private Blue Train segment (reserved carriage)",
      "Full-day Ayurveda consultation + treatments",
      "Cooking class in Ella",
      "Private sunset seafood BBQ on the beach",
      "Airport pickup & drop-off",
      "24/7 WhatsApp support",
    ],
    excluded: [
      "International flights",
      "Visa (ETA, ~USD 50 online)",
      "Optional whale watching (USD 45 pp)",
      "Alcoholic drinks",
      "Travel insurance",
      "Optional tips",
    ],
  },
  {
    slug: "quick-escape",
    label: "Weekend Warrior",
    title: "Quick Escape",
    tagline: "5 days, all the essentials, zero rush.",
    days: 5,
    durationLabel: "5 days",
    durationGroup: "3-5",
    tags: ["couples", "adventure"],
    tagLabels: ["Couples", "Adventure"],
    price: { USD: 690, GBP: 545, EUR: 630 },
    priceNote: "per person, twin share",
    blurb:
      "Flying in from Singapore or Dubai for a long weekend? This is the sharpest taste of Sri Lanka we can give you in 5 days.",
    image:
      "https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1Nzh8MHwxfHNlYXJjaHwxfHxzcmklMjBsYW5rYSUyMHRyYWlufGVufDB8fHx8MTc3NjQ4NDAwM3ww&ixlib=rb-4.1.0&q=85",
    highlights: [
      "Sigiriya Rock sunrise climb",
      "Blue Train ride (Kandy → Ella)",
      "One night in a tea-estate bungalow",
      "Beach-day reward at Mirissa",
    ],
    itinerary: [
      { day: 1, title: "Colombo → Sigiriya", desc: "Airport pickup, direct drive north. Dambulla cave temples at sunset.", meals: "Dinner", stay: "Sigiriya eco-lodge" },
      { day: 2, title: "Sigiriya sunrise → Kandy", desc: "Climb Sigiriya at dawn, drive to Kandy via spice gardens.", meals: "Breakfast", stay: "Kandy guesthouse" },
      { day: 3, title: "Kandy → Hill Country (Blue Train)", desc: "Temple of the Tooth, board the train to Ella.", meals: "Breakfast", stay: "Tea bungalow" },
      { day: 4, title: "Ella → Mirissa beach", desc: "Nine Arches morning, then scenic drive to the south coast for sunset.", meals: "Breakfast", stay: "Beach villa" },
      { day: 5, title: "Beach morning & flight home", desc: "Slow breakfast, quick swim, airport transfer.", meals: "Breakfast", stay: "—" },
    ],
    included: [
      "Private vehicle + driver-guide",
      "4 nights in mixed accommodation",
      "Daily breakfast + 1 dinner",
      "Blue Train reserved seat",
      "Sigiriya, Dambulla, Temple of the Tooth entries",
      "Airport transfers",
      "24/7 WhatsApp support",
    ],
    excluded: [
      "International flights",
      "Visa (ETA, ~USD 50)",
      "Most lunches & dinners",
      "Alcoholic drinks",
      "Travel insurance",
      "Optional tips",
    ],
  },
];

export const FILTERS = {
  duration: [
    { id: "all", label: "All" },
    { id: "3-5", label: "3–5 Days" },
    { id: "6-8", label: "6–8 Days" },
    { id: "9+", label: "9+ Days" },
  ],
  type: [
    { id: "couples", label: "Couples" },
    { id: "family", label: "Family" },
    { id: "solo", label: "Solo" },
    { id: "adventure", label: "Adventure" },
    { id: "wellness", label: "Wellness" },
  ],
};

export const CURRENCIES = [
  { code: "USD", symbol: "$" },
  { code: "GBP", symbol: "£" },
  { code: "EUR", symbol: "€" },
];

export const getPackageBySlug = (slug) => PACKAGES.find((p) => p.slug === slug);
